// config/iconOptions.ts
import {
  AccessAlarm,
  Accessibility,
  AccountBalance,
  AccountCircle,
  AddShoppingCart,
  Alarm,
  Apartment,
  Apps,
  Assessment,
  AttachMoney,
  AutoGraph,
  Backup,
  BarChart,
  BatteryChargingFull,
  BeachAccess,
  Bedtime,
  Bookmark,
  Book,
  BugReport,
  Build,
  CalendarMonth,
  CameraAlt,
  Chat,
  CheckCircle,
  CleanHands,
  Cloud,
  Code,
  Commute,
  Computer,
  ContentPaste,
  CreditCard,
  Dashboard,
  Delete,
  Description,
  DirectionsBike,
  DirectionsRun,
  Download,
  Edit,
  Email,
  EmojiEmotions,
  Event,
  Explore,
  Extension,
  Face,
  Facebook,
  Favorite,
  FileCopy,
  FitnessCenter,
  Flight,
  Folder,
  FoodBank,
  FormatPaint,
  Forum,
  Games,
  Grade,
  Group,
  Headphones,
  HealthAndSafety,
  Home,
  Hotel,
  Image,
  Info,
  Instagram,
  Keyboard,
  Language,
  LightMode,
  Link,
  List,
  LocalActivity,
  LocalCafe,
  LocalDining,
  LocalLibrary,
  Lock,
  Map,
  MenuBook,
  Mood,
  Movie,
  MusicNote,
  Nature,
  Nightlight,
  Note,
  Notifications,
  Park,
  Payment,
  People,
  Pets,
  Photo,
  Place,
  PlayArrow,
  Poll,
  Psychology,
  Radio,
  Restaurant,
  RocketLaunch,
  Savings,
  School,
  Science,
  Search,
  SelfImprovement,
  Settings,
  ShoppingCart,
  ShowChart,
  Spa,
  SportsBasketball,
  SportsEsports,
  Star,
  Store,
  Support,
  ThumbUp,
  Timer,
  TrendingUp,
  Tv,
  WaterDrop,
  Whatshot,
  Work,
  YouTube,
  type SvgIconComponent,
} from "@mui/icons-material";

export interface IconOption {
  name: string;
  icon: SvgIconComponent;
}

export const ICON_OPTIONS: IconOption[] = [
  { name: "Access Alarm", icon: AccessAlarm },
  { name: "Accessibility", icon: Accessibility },
  { name: "Account Balance", icon: AccountBalance },
  { name: "Account Circle", icon: AccountCircle },
  { name: "Add Shopping Cart", icon: AddShoppingCart },
  { name: "Alarm", icon: Alarm },
  { name: "Apartment", icon: Apartment },
  { name: "Apps", icon: Apps },
  { name: "Assessment", icon: Assessment },
  { name: "Attach Money", icon: AttachMoney },
  { name: "Auto Graph", icon: AutoGraph },
  { name: "Backup", icon: Backup },
  { name: "Bar Chart", icon: BarChart },
  { name: "Battery Charging", icon: BatteryChargingFull },
  { name: "Beach Access", icon: BeachAccess },
  { name: "Bedtime", icon: Bedtime },
  { name: "Bookmark", icon: Bookmark },
  { name: "Book", icon: Book },
  { name: "Bug Report", icon: BugReport },
  { name: "Build", icon: Build },
  { name: "Calendar", icon: CalendarMonth },
  { name: "Camera", icon: CameraAlt },
  { name: "Chat", icon: Chat },
  { name: "Check Circle", icon: CheckCircle },
  { name: "Clean Hands", icon: CleanHands },
  { name: "Cloud", icon: Cloud },
  { name: "Code", icon: Code },
  { name: "Commute", icon: Commute },
  { name: "Computer", icon: Computer },
  { name: "Content Paste", icon: ContentPaste },
  { name: "Credit Card", icon: CreditCard },
  { name: "Dashboard", icon: Dashboard },
  { name: "Delete", icon: Delete },
  { name: "Description", icon: Description },
  { name: "Directions Bike", icon: DirectionsBike },
  { name: "Directions Run", icon: DirectionsRun },
  { name: "Download", icon: Download },
  { name: "Edit", icon: Edit },
  { name: "Email", icon: Email },
  { name: "Emoji Emotions", icon: EmojiEmotions },
  { name: "Event", icon: Event },
  { name: "Explore", icon: Explore },
  { name: "Extension", icon: Extension },
  { name: "Face", icon: Face },
  { name: "Facebook", icon: Facebook },
  { name: "Favorite", icon: Favorite },
  { name: "File Copy", icon: FileCopy },
  { name: "Fitness Center", icon: FitnessCenter },
  { name: "Flight", icon: Flight },
  { name: "Folder", icon: Folder },
  { name: "Food Bank", icon: FoodBank },
  { name: "Format Paint", icon: FormatPaint },
  { name: "Forum", icon: Forum },
  { name: "Games", icon: Games },
  { name: "Grade", icon: Grade },
  { name: "Group", icon: Group },
  { name: "Headphones", icon: Headphones },
  { name: "Health And Safety", icon: HealthAndSafety },
  { name: "Home", icon: Home },
  { name: "Hotel", icon: Hotel },
  { name: "Image", icon: Image },
  { name: "Info", icon: Info },
  { name: "Instagram", icon: Instagram },
  { name: "Keyboard", icon: Keyboard },
  { name: "Language", icon: Language },
  { name: "Light Mode", icon: LightMode },
  { name: "Link", icon: Link },
  { name: "List", icon: List },
  { name: "Local Activity", icon: LocalActivity },
  { name: "Local Cafe", icon: LocalCafe },
  { name: "Local Dining", icon: LocalDining },
  { name: "Local Library", icon: LocalLibrary },
  { name: "Lock", icon: Lock },
  { name: "Map", icon: Map },
  { name: "Menu Book", icon: MenuBook },
  { name: "Mood", icon: Mood },
  { name: "Movie", icon: Movie },
  { name: "Music Note", icon: MusicNote },
  { name: "Nature", icon: Nature },
  { name: "Nightlight", icon: Nightlight },
  { name: "Note", icon: Note },
  { name: "Notifications", icon: Notifications },
  { name: "Park", icon: Park },
  { name: "Payment", icon: Payment },
  { name: "People", icon: People },
  { name: "Pets", icon: Pets },
  { name: "Photo", icon: Photo },
  { name: "Place", icon: Place },
  { name: "Play Arrow", icon: PlayArrow },
  { name: "Poll", icon: Poll },
  { name: "Psychology", icon: Psychology },
  { name: "Radio", icon: Radio },
  { name: "Restaurant", icon: Restaurant },
  { name: "Rocket Launch", icon: RocketLaunch },
  { name: "Savings", icon: Savings },
  { name: "School", icon: School },
  { name: "Science", icon: Science },
  { name: "Search", icon: Search },
  { name: "Self Improvement", icon: SelfImprovement },
  { name: "Settings", icon: Settings },
  { name: "Shopping Cart", icon: ShoppingCart },
  { name: "Show Chart", icon: ShowChart },
  { name: "Spa", icon: Spa },
  { name: "Sports Basketball", icon: SportsBasketball },
  { name: "Sports Esports", icon: SportsEsports },
  { name: "Star", icon: Star },
  { name: "Store", icon: Store },
  { name: "Support", icon: Support },
  { name: "Thumb Up", icon: ThumbUp },
  { name: "Timer", icon: Timer },
  { name: "Trending Up", icon: TrendingUp },
  { name: "TV", icon: Tv },
  { name: "Water Drop", icon: WaterDrop },
  { name: "Whatshot", icon: Whatshot },
  { name: "Work", icon: Work },
  { name: "YouTube", icon: YouTube },
];
